global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/slo-rules.yml
  - /etc/prometheus/alert-rules.yml

scrape_configs:
  - job_name: shard-router
    static_configs:
      - targets: ['shard-router:8080']
    metrics_path: /metrics

  - job_name: saga-hub
    static_configs:
      - targets: ['saga-hub:9090']
    metrics_path: /metrics

  - job_name: cell-pedidos
    static_configs:
      - targets:
          - 'cell-pedidos-s1-active:8000'
          - 'cell-pedidos-s2-active:8000'
          - 'cell-pedidos-s3-active:8000'
    metrics_path: /metrics

  - job_name: cell-estoque
    static_configs:
      - targets:
          - 'cell-estoque-s1-active:8000'
          - 'cell-estoque-s2-active:8000'
          - 'cell-estoque-s3-active:8000'
    metrics_path: /metrics

  - job_name: cell-notificacoes
    static_configs:
      - targets:
          - 'cell-notif-s1-active:8000'
          - 'cell-notif-s2-active:8000'
          - 'cell-notif-s3-active:8000'
    metrics_path: /metrics
