global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: cell-pedidos
    static_configs:
      - targets: ["cell-pedidos:8000"]
    metrics_path: /metrics

  - job_name: cell-estoque
    static_configs:
      - targets: ["cell-estoque:8000"]
    metrics_path: /metrics

  - job_name: cell-notificacoes
    static_configs:
      - targets: ["cell-notificacoes:8000"]
    metrics_path: /metrics

  - job_name: agent-mcp
    static_configs:
      - targets: ["agent-mcp:9000"]
    metrics_path: /metrics

  - job_name: traefik
    static_configs:
      - targets: ["api-gateway:8080"]
    metrics_path: /metrics
