apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonLabels:
  environment: production

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: shard-router
        namespace: poc-eci
      spec:
        replicas: 3
        template:
          spec:
            containers:
              - name: shard-router
                resources:
                  requests:
                    cpu: "200m"
                    memory: "256Mi"
                  limits:
                    cpu: "1"
                    memory: "512Mi"
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: saga-hub
        namespace: poc-eci
      spec:
        replicas: 2
        template:
          spec:
            containers:
              - name: saga-hub
                resources:
                  requests:
                    cpu: "200m"
                    memory: "256Mi"
                  limits:
                    cpu: "1"
                    memory: "512Mi"

# Set via CI: kustomize edit set image poc-eci/cell-pedidos=registry/cell-pedidos:${VERSION}
images:
  - name: poc-eci/shard-router
    newTag: latest
  - name: poc-eci/saga-hub
    newTag: latest
  - name: poc-eci/cell-pedidos
    newTag: latest
  - name: poc-eci/cell-estoque
    newTag: latest
  - name: poc-eci/cell-notificacoes
    newTag: latest
