apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: poc-eci

resources:
  - namespace.yaml
  - network-policy.yaml
  - ingress.yaml
  - cert-issuer.yaml
  - ../core/saga-hub.yaml
  - ../core/shard-router.yaml
  - ../core/data-sync.yaml
  - ../core/debezium-init-job.yaml
  - ../core/pg-backup-cronjob.yaml
  - ../shards/shard-1
  - ../shards/shard-2
  - ../shards/shard-3

commonLabels:
  app.kubernetes.io/part-of: poc-eci
  app.kubernetes.io/managed-by: kustomize
