apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: ""
nameSuffix: ""

commonLabels:
  environment: staging

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: shard-router
        namespace: poc-eci
      spec:
        replicas: 1
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: saga-hub
        namespace: poc-eci
      spec:
        replicas: 1

images:
  - name: poc-eci/shard-router
    newTag: staging
  - name: poc-eci/saga-hub
    newTag: staging
  - name: poc-eci/cell-pedidos
    newTag: staging
  - name: poc-eci/cell-estoque
    newTag: staging
  - name: poc-eci/cell-notificacoes
    newTag: staging
